---
# Defines which king of aggregation should be used. Available options are "status" and "severity"
messageType: status
avatarURL: https://raw.githubusercontent.com/masgustavos/alertmanager-discord/master/assets/images/prometheus-logo.png
username: alertmanager-discord-webhook
firingCountToMention: -1
status:
  firing:
    emoji: ":x:"
    color: 10038562 #EmbedColorDarkRed
  resolved:
    emoji: ":white_check_mark:"
    color: 3066993 # EmbedColorGreen
severity:
  label: severity
  values:
    unknown:
      color: 9807270 # EmbedColorGrey
      emoji: ":grey_question:"
    information:
      color: 3447003 # EmbedColorBlue
      emoji: ":information_source:"
    warning:
      color: 15844367 # EmbedColorGold
      emoji: ":warning:"
    critical:
      color: 11027200 # EmbedColorDarkOrange
      emoji: ":x:"
    disaster:
      color: 10038562 # EmbedColorDarkRed
      emoji: ":fire:"
