version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CONFIG_PATH: "./my-config.yaml"
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ./:/app

  prometheus:
    image: prom/prometheus:v2.24.1
    volumes:
      - ./mock/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./mock/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yaml"
      - "--storage.path=/alertmanager"
